services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf:/etc/nginx/templates/default.conf.template

    ports:
      - "80:80"

  server:
    build: ./server
    restart: unless-stopped
    volumes:
      - ./server/src:/app/src
      - /app/src/node_modules
    environment:
      - PORT=80


  client:
    build: ./client
    restart: unless-stopped
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - PORT=80
      - CHOKIDAR_USEPOLLING=true